name: Build & Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=RELEASE -DTEST=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config RELEASE

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }} release
          path: ${{github.workspace}}/build/Release/*
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
      - name: Zip artifacts for release
        run: |
          for i in */; do zip -r "${i%/}.zip" "$i"; done
        working-directory: artifacts
      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          name: Latest Commit
          tag_name: latest-commit
          body: ${{ github.event.head_commit.message }}
          files: artifacts/*
